services:
  postgres:
    image: postgres:14.2-alpine
    restart: always
    environment:
      POSTGRES_DB: vidracaria
      POSTGRES_PASSWORD: 12345
      POSTGRES_USER: user
    ports:
      - '5432'

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - '5050:80'
